Feature/async await support
MrSkwiggs/Netswift pull request #34
Opened 2021-11-18 16:00 UTC by Deco354

2021-11-26 21:57 UTC, MrSkwiggs requested changes
Thanks a lot for your contribution @Deco354, it is greatly appreciated :)

For the most part I'm very happy with the proposed changes; the code is pretty straightforward and covers the basic Netswift API.

You did however left me scratching my head with some decisions you took with your use of `checkedContinuation` when you could've just called your own, newly implemented `async` functions 🤔 

At any rate, I've provided some suggestions for those cases, as well as some additional comments. 
Please review them and let me know. Once all those points are resolved I'm more than happy to merge this 👍

2021-11-26 21:57 UTC, MrSkwiggs commented on Example/Netswift/API/API.swift
> +    @available(iOS 15.0.0, *)
```suggestion
    @available(iOS 15, *)
```

2021-11-26 21:57 UTC, MrSkwiggs commented on Sources/Netswift/Core/HTTPPerformer.swift
> +     Performs a standard URL request and returns the results via a completion handler
👍  🙈

2021-11-26 21:57 UTC, MrSkwiggs commented on Sources/Netswift/Core/HTTPPerformer.swift
> +     Performs a standard URL request and returns the results asyncronously
```suggestion
     Performs a standard URL request and returns the results asynchronously
```

2021-11-26 21:57 UTC, MrSkwiggs commented on Sources/Netswift/Core/HTTPPerformer.swift
> +     Performs a standard URL request and returns the results asyncronusly
```suggestion
     Performs a standard URL request and returns the results asynchronously
```

2021-11-26 21:57 UTC, MrSkwiggs commented on Sources/Netswift/Core/NetswiftNetworkPerformer.swift
> +    func perform<T: NetswiftRequest>(_ request: T) async -> NetswiftResult<T.Response>
This is missing documentation (but can simply be copy-pasted with relevant edits from non-async variant)

2021-11-26 21:57 UTC, MrSkwiggs commented on Sources/Netswift/NetswiftHTTPPerformer.swift
> +        }
While this will work out of the box, I would actually expect the `NetswiftSession` to also offer an async API.
This would considerably simply this callsite:
```swift
await validate(session.perform(request))
```

2021-11-26 21:57 UTC, MrSkwiggs commented on Sources/Netswift/NetswiftHTTPPerformer.swift
> +        }
Same here (with the equivalent of setting an async deadline to return by)

2021-11-26 21:57 UTC, MrSkwiggs commented on Sources/Netswift/NetswiftPerformer.swift
> +        }
I'm confused here as to why you didn't actually use the `async` HTTPPerformer api you just implemented? 🤔 
```suggestion
        switch request.serialise() {
        case .success(let url):
            switch await requestPerformer.perform(url) {
            case .success:
                return response
                    .flatMap(request.decode)
                    .flatMap(request.cast)
                    .flatMap(request.deserialise)
                    
                case .failure(let error):
                    return .failure(error)
            }
            
        case .failure(let error):
            return .failure(error)
        }
```

2021-12-12 17:24 UTC, Deco354 commented on Sources/Netswift/NetswiftHTTPPerformer.swift
> +        }
Unfortunately timeouts don't appear to be supported out the box by either `DispatchGroup` or `TaskGroup` at present.

There is an interesting [thread](https://forums.swift.org/t/running-an-async-task-with-a-timeout/49733) and an [article](https://alejandromp.com/blog/the-importance-of-cooperative-cancellation/) by one of Swift's contributors on how to implement this but I think it warrants its own PR as the intent of this PR is just to convert the public facing API of NetSwift rather than convert all internal functions.

Definitely something I'd be interested in doing at a later date as this is pretty fundamental functionality I'm surprised isn't supported out the box. If you do find a Swift library implementation for this though let me know and I'll be happy to swap it out.

2021-12-13 02:55 UTC, MrSkwiggs commented on Sources/Netswift/NetswiftHTTPPerformer.swift
> +        }
That's fine for now then, the rest of the implementation is good to go 👍 Thanks!

2021-12-13 02:56 UTC, MrSkwiggs approved these changes
👍  ready to go

2021-12-13 04:07 UTC, merged